apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fineract-server-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: d6-platform
    kind: ClusterSecretStore
  target:
    name: fineract-server-secret
  data:
    - secretKey: FINERACT_HIKARI_USERNAME
      remoteRef:
        key: fineract_server_config
        property: FINERACT_HIKARI_USERNAME
    - secretKey: FINERACT_DEFAULT_TENANTDB_UID
      remoteRef:
        key: fineract_server_config
        property: FINERACT_DEFAULT_TENANTDB_UID
    - secretKey: FINERACT_HIKARI_PASSWORD
      remoteRef:
        key: fineract_server_config
        property: FINERACT_HIKARI_PASSWORD
    - secretKey: FINERACT_DEFAULT_TENANTDB_PWD
      remoteRef:
        key: fineract_server_config
        property: FINERACT_DEFAULT_TENANTDB_PWD
