apiVersion: v1
kind: Service
metadata:
  name: fineract-api-svc
spec:
  selector:
    app: fineract
    tier: backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: fineract-ui-svc
spec:
  selector:
    app: fineract
    tier: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
